/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as BlogIndexImport } from './routes/blog/index'
import { Route as BlogLayoutImport } from './routes/blog/_layout'
import { Route as BlogBlogidImport } from './routes/blog/$blogid'

// Create Virtual Routes

const BlogImport = createFileRoute('/blog')()

// Create/Update Routes

const BlogRoute = BlogImport.update({
  path: '/blog',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BlogIndexRoute = BlogIndexImport.update({
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)

const BlogLayoutRoute = BlogLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => BlogRoute,
} as any)

const BlogBlogidRoute = BlogBlogidImport.update({
  path: '/blog/$blogid',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/blog/$blogid': {
      id: '/blog/$blogid'
      path: '/blog/$blogid'
      fullPath: '/blog/$blogid'
      preLoaderRoute: typeof BlogBlogidImport
      parentRoute: typeof rootRoute
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogImport
      parentRoute: typeof rootRoute
    }
    '/blog/_layout': {
      id: '/blog/_layout'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogLayoutImport
      parentRoute: typeof BlogRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexImport
      parentRoute: typeof BlogImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  LoginRoute,
  BlogBlogidRoute,
  BlogRoute: BlogRoute.addChildren({ BlogIndexRoute }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/blog/$blogid",
        "/blog"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/blog/$blogid": {
      "filePath": "blog/$blogid.tsx"
    },
    "/blog": {
      "filePath": "blog",
      "children": [
        "/blog/_layout",
        "/blog/"
      ]
    },
    "/blog/_layout": {
      "filePath": "blog/_layout.tsx",
      "parent": "/blog"
    },
    "/blog/": {
      "filePath": "blog/index.tsx",
      "parent": "/blog"
    }
  }
}
ROUTE_MANIFEST_END */
